apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: appmanager-server-env
data:
  APPMANAGER_DB_HOST: 'rm-8vbo5942x7hjna4v8.mysql.zhangbei.rds.aliyuncs.com'
  APPMANAGER_DB_PORT: '3306'
  APPMANAGER_DB_USER: 'appmanager'
  APPMANAGER_DB_PASSWORD: 'xFyLeqNkQKT8'
  APPMANAGER_DB_NAME: 'appmanager'
  APPMANAGER_PACKAGE_DRIVER: 'oss'
  APPMANAGER_PACKAGE_ENDPOINT: 'oss-cn-zhangjiakou.aliyuncs.com'
  APPMANAGER_PACKAGE_ACCESS_KEY: 'xxx'
  APPMANAGER_PACKAGE_SECRET_KEY: 'xxx'
  APPMANAGER_PACKAGE_BUCKET_NAME: 'appmanager-daily'
  APPMANAGER_DAG_BUCKET_NAME: 'appmanager-daily-dag'
  APPMANAGER_REDIS_HOST: 'r-8vb509baef4beec4.redis.zhangbei.rds.aliyuncs.com'
  APPMANAGER_REDIS_PORT: '6379'
  APPMANAGER_REDIS_DATABASE: '0'
  APPMANAGER_REDIS_PASSWORD: '7FUFg6vuuQgh'
  APPMANAGER_ENV: 'daily'
  REMOTE_DOCKER_DAEMON: 'tcp://11.158.188.56:2375'
  DOCKER_REGISTRY: 'reg.docker.alibaba-inc.com'
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: appmanager-db-migration-env
data:
  DB_HOST: 'rm-8vbo5942x7hjna4v8.mysql.zhangbei.rds.aliyuncs.com'
  DB_PORT: '3306'
  DB_USER: 'appmanager'
  DB_PASSWORD: 'xFyLeqNkQKT8'
  DB_NAME: 'appmanager'
