apiVersion: apps/v1
kind: StatefulSet
metadata:
  name:  {{ .Release.Name }}-registry
spec:
  serviceName: "registry"
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: docker-registry
        image: registry
        ports:
        - containerPort: 5000
          name: registry-port
          protocol: TCP
        volumeMounts:
        - name: docker-registry-data
          mountPath: /var/lib/registry/
  volumeClaimTemplates:
  - metadata:
      name: docker-registry-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.global.storageClass }} 
      resources:
        requests:
          storage: 100Gi


