apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-registry
spec:
  type: ClusterIP
  ports:
  ports:
    - name: registry-port
      port: 5000 
      protocol: TCP
      targetPort: 5000
  selector:
    app: registry
