apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: ilogtail.trait.abm.io
spec:
  className: com.alibaba.tesla.appmanager.trait.plugin.IlogtailTrait
  runtime: pre
  appliesToWorkloads:
    - "*"
  definitionRef:
    name: ilogtail.k8s.schema.abm.io
  example:
    userId: "2341231"
    userDefinedId: "test-user-id"
    regionId: cn-zhangjiakou
    volumeMounts:
      - name: server-pvc
        mountPath: /app/logs
