apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: podSecurityContext.trait.abm.io
spec:
  className: com.alibaba.tesla.appmanager.trait.plugin.PodSecurityContextTrait
  runtime: post
  appliesToWorkloads:
    - "*"
  definitionRef:
    name: podSecurityContext.k8s.schema.abm.io
  example:
    fsGroup: 101
