
minio:
  enabled: false

mysql:
  enabled: false

redis:
  enabled: false

zookeeper:
  enabled: false

ingressNginx:
  enabled: false

kruise:
  enabled: true

rocketmq:
  enabled: false

kafka:
  enabled: false

harbor:
  enabled: false

registry:
  enabled: false


