apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: containerPatch.trait.abm.io
spec:
  className: com.alibaba.tesla.appmanager.trait.plugin.ContainerPatchTrait
  runtime: pre
  appliesToWorkloads:
    - "*"
  definitionRef:
    name: containerPatch.k8s.schema.abm.io
  example:
    securityContext:
      capabilities:
        drop:
          - ALL
        add:
          - NET_BIND_SERVICE
      runAsUser: 101
      allowPrivilegeEscalation: true
    lifecycle:
      preStop:
        exec:
          command:
            - /wait-shutdown