apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: gateway.trait.abm.io
spec:
  className: com.alibaba.tesla.appmanager.trait.plugin.GatewayTrait
  runtime: pre
  appliesToWorkloads:
    - "*"
  definitionRef:
    name: gateway.k8s.schema.abm.io
