apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: hellopost.trait.abm.io
spec:
  className: com.alibaba.tesla.appmanager.trait.plugin.HelloPostTrait
  runtime: pre
  appliesToWorkloads:
    - "*"
  definitionRef:
    name: hellopost.schema.abm.io
  example:
    helloKey: helloValue
  dataOutputs:
    - name: helloOutput
      fieldPath: "{{ spec.helloKey }}"
      applyFieldPaths:
        - "spec.h1"
        - "spec.h2.h3"
