apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: pvc.trait.abm.io
spec:
  className: com.alibaba.tesla.appmanager.trait.plugin.PvcTrait
  runtime: pre
  appliesToWorkloads:
    - "*"
  definitionRef:
    name: pvc.k8s.schema.abm.io
  example:
    targets:
      - initContainer: db-migration
        pvc: pvc1
        mountPath: /root/aa
      - container: server
        mountPath: /root/bbb
        pvc: pvc2
    pvcs:
      pvc1:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "my-storage-class"
        resources:
          requests:
            storage: 1Gi
      pvc2:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "my-storage-class"
        resources:
          requests:
            storage: 1Gi