version: "3.8"

services:

  mysql:
    image: bitnami/mysql:8.0
    container_name: mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
      - MYSQL_DATABASE=appmanager
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "-u$$MYSQL_ROOT_USER", "-p$$MYSQL_ROOT_PASSWORD",  "ping", "-h", "localhost" ]
      interval: 3s
      timeout: 1s
      retries: 16
      start_period: 30s
    volumes:
      - ../mysql/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf
      - ../mysql/init.d:/docker-entrypoint-initdb.d
    networks:
      - appmanager

  redis:
    image: bitnami/redis:7.0.10
    container_name: redis
    environment:
      - REDIS_PORT_NUMBER=6379
      - REDIS_PASSWORD=123456
    ports:
      - 6379:6379
    networks:
      - appmanager

  minio:
    image: bitnami/minio:2025.4.8
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DEFAULT_BUCKETS=sreworks-appmanager:public,sreworks-appmanager-dag:public
      - MINIO_PROMETHEUS_AUTH_TYPE=public # 低版本不起效，升级到最新版本
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - appmanager

  sw-paas-appmanager-db-migration:
    image: sreworks-registry.cn-beijing.cr.aliyuncs.com/hub/sw-paas-appmanager-db-migration:v1.5
    container_name: sw-paas-appmanager-db-migration
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=sreworks_appmanager
    networks:
      - appmanager

  sw-paas-appmanager:
    image: sreworks-registry.cn-beijing.cr.aliyuncs.com/hub/sw-paas-appmanager:v1.5
    container_name: sw-paas-appmanager
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      APPMANAGER_DB_HOST: "mysql"
      APPMANAGER_DB_PORT: "3306"
      APPMANAGER_DB_USER: "root"
      APPMANAGER_DB_PASSWORD: "123456"
      APPMANAGER_DB_NAME: "sreworks_appmanager"
      APPMANAGER_PACKAGE_DRIVER: "minio"
      APPMANAGER_PACKAGE_ENDPOINT: "minio:9000"
      APPMANAGER_PACKAGE_ENDPOINT_PROTOCOL: "http://"
      APPMANAGER_PACKAGE_ACCESS_KEY: "admin"
      APPMANAGER_PACKAGE_SECRET_KEY: "password"
      APPMANAGER_PACKAGE_BUCKET_NAME: "sreworks-appmanager"
      APPMANAGER_DAG_BUCKET_NAME: "sreworks-appmanager-dag"
      APPMANAGER_REDIS_HOST: "redis"
      APPMANAGER_REDIS_PORT: "6379"
      APPMANAGER_REDIS_DATABASE: "2"
      APPMANAGER_REDIS_PASSWORD: "123456"
      APPMANAGER_ENV: "daily"
      APPMANAGER_ROCKETMQ_NAMESRV_ENDPOINT: "sreworks-name-server-service:9876"
      APPMANAGER_ENABLE_AUTH: false
      APPMANAGER_ACCESS_ID: "superuser"
      APPMANAGER_ACCESS_SECRET: "yJfIYmjAiCL0ondV3kY7e5x6kVTpvC3h"
      APPMANAGER_CLIENT_ID: "superclient"
      APPMANAGER_CLIENT_SECRET: "stLCjCPKbWmki65DsAj2jPoeBLPimpJa"
      APPMANAGER_JWT_SECRET_KEY: "3d8e06065426"
      ABM_CLUSTER: daily
    ports:
      - 7004:7001
    networks:
      - appmanager

  flycore-paas-nacos-db-migration:
    image: sreworks-registry.cn-beijing.cr.aliyuncs.com/hub/flycore-paas-nacos-db-migration:1692362620981
    container_name: flycore-paas-nacos-db-migration
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=abm_paas_nacos
    networks:
      - appmanager

  flycore-paas-nacos-paas-nacos:
    image: sreworks-registry.cn-beijing.cr.aliyuncs.com/hub/flycore-paas-nacos-paas-nacos:1692362620981
    container_name: flycore-paas-nacos-paas-nacos
    environment:
      - MYSQL_MASTER_SERVICE_HOST=mysql
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_MASTER_SERVICE_USER=root
      - MYSQL_MASTER_SERVICE_PASSWORD=123456
      - MYSQL_MASTER_SERVICE_DB_NAME=abm_paas_nacos
    ports:
      - 8848:8848
    networks:
      - appmanager

  flycore-paas-gateway-paas-gateway:
    image: sreworks-registry.cn-beijing.cr.aliyuncs.com/hub/flycore-paas-gateway-paas-gateway:1692362620981
    container_name: flycore-paas-gateway-paas-gateway
    environment:
      REGISTER_NACOS_ENABLED: false
      NACOS_ENDPOINT: flycore-paas-nacos-paas-nacos:7001
      NACOS_NAMESPACE: paas-gateway:7001
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 3
      REDIS_PASSWORD: 123456
      GATEWAY_ENABLE_AUTH: false
    ports:
      - 7001:7001
    networks:
      - appmanager

  flycore-paas-frontend-paas-frontend:
    image: sreworks-registry.cn-beijing.cr.aliyuncs.com/hub/flycore-paas-frontend-paas-frontend:1692362620981
    container_name: frontend
    environment:
      ENDPOINT_PAAS_GATEWAY: flycore-paas-gateway-paas-gateway:7001
      DNS_PAAS_HOME: appmanager
    ports:
      - 8089:80
    networks:
      - appmanager

networks:
  appmanager:
    driver: bridge