global:
  storageClass: "alicloud-disk-available"

home:
  url: "https://sreworks.ingress.com"
  endpoint: 

operator:
  globalListener: true

images:
  registry:  sreworks-registry.cn-beijing.cr.aliyuncs.com/sreworks
  tag: v0.5
  imagePullPolicy: Always 

  #operator: registry.cn-hangzhou.aliyuncs.com/alisre/sw-paas-appmanager-operator:develop
  #dbMigration: registry.cn-hangzhou.aliyuncs.com/alisre/sw-paas-appmanager-db-migration:develop
  #postrun: registry.cn-hangzhou.aliyuncs.com/alisre/sw-paas-appmanager-postrun:develop
  #clusterInitJob: registry.cn-hangzhou.aliyuncs.com/alisre/sw-paas-appmanager-cluster-init:develop
  
  kaniko: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/kaniko-executor:latest
  rbacProxy: sreworks-registry.cn-beijing.cr.aliyuncs.com/mirror/kube-rbac-proxy:v0.8.0

server:
  rbac: admin
  database:
    #host: 
    port: 3306
    user: 'root'
    password: 'bGuwsAWQM6K'
    name: daily_appmanager
  rocketmq:
    namesrv: 
  package:
    driver: "minio"
    #endpoint: 
    accessKey: "XmizyTRKhgYTrVkK"
    secretKey: "Df229gtwZ4bssMzK23VJXq9vrGqpxdHA"
    bucketName: "abm-oxs-appmanager-daily"
  dag:
    bucketName: "abm-oxs-appmanager-daily-dag"
  redis:
    #host:
    port: 6379
    database: 1
    password: 'siJEULmQYQ'
  env: "daily"
  cloudType: "PaaS"
  cluster: "DAILY"
  jvmXMX: "4000m"
  accessId: superuser
  accessSecret: yJfIYmjAiCL0ondV3kY7e5x6kVTpvC3h
  clientId: superclient
  clientSecret: stLCjCPKbWmki65DsAj2jPoeBLPimpJa
  jwtSecretKey: 3d8e06065426
  kafkaBrokerPort: 9092
  enableAuth: true
  docker:
    enableKaniko: true
    secret: "server-docker-secret"
    account: sreworks
    password: sreworksDocker123q
    registry: registry.cn-zhangjiakou.aliyuncs.com
    namespace: builds

installMode: default



