t-tesla-framework-faas:
  pkgpara:
    DOCKER: 1
t-tesla-framework-faas-ApsaraStack-V38:
  pkgpara:
    DOCKER: 1
t-tesla-framework-faas-OXS:
  pkgpara:
    DOCKER: 1
t-tesla-framework-faas-Standalone:
  pkgpara:
    DOCKER: 1
