global:
  storageClass: "alicloud-disk-available"

  minio:
    existingSecret: ""
    accessKey: 'XmizyTRKhgYTrVkK'
    secretKey: 'Df229gtwZ4bssMzK23VJXq9vrGqpxdHA'

minio:
  enabled: true

  service:
    type: ClusterIP
  image:
    registry: registry.cn-hangzhou.aliyuncs.com
    repository: alisre/minio
    tag: v1
  
  persistence:
    size: 500Gi

mysql:
  enabled: true

  primary:
    service:
      type: ClusterIP
    persistence:
      size: 200Gi
    extraFlags: "--max-connect-errors=1000 --max_connections=10000"


  replication:
    enabled: false

  image:
    registry: registry.cn-hangzhou.aliyuncs.com
    repository: alisre/mysql
    tag: v1

  auth:
    rootPassword: 'bGuwsAWQM6K'


redis:
  enabled: true

  cluster:
    enabled: false

  password: 'siJEULmQYQ'

  master:
    service:
      type: ClusterIP
    disableCommands: 
      - FLUSHDB
    persistence:
      size: 50Gi
    
  image:
    registry: registry.cn-hangzhou.aliyuncs.com
    repository: alisre/redis
    tag: v1
  

zookeeper:
  enabled: true

  image:
    registry: registry.cn-hangzhou.aliyuncs.com
    repository: alisre/zookeeper
    tag: v1
 
  persistence:
    size: 50Gi

ingressNginx:
  enabled: false

kruise:
  enabled: true

kafka:
  enabled: true

  persistence:
    size: 500Gi

  image:
    registry: sreworks-registry.cn-beijing.cr.aliyuncs.com
    repository: mirror/kafka

  zookeeper:
    enabled: false

  externalZookeeper:
    servers: "sreworks-zookeeper:2181"

harbor:
  enabled: false

registry:
  enabled: false

