{{- if eq .Values.installMode "default" -}}
{{- $auth := printf "%s:%s" .Values.server.docker.account .Values.server.docker.password | b64enc -}}
{{- $dockerconfigjson := printf "{\"auths\":{\"%s\":{\"auth\":\"%s\"}}}" .Values.server.docker.registry $auth | b64enc -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.server.docker.secret }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $dockerconfigjson }}
{{- end -}}
